# The URL the site will be built for
base_url = "https://mostro.network/blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

title = "Mostro blog"
description = "Fresh updates, insights, and news straight from the Mostro team."

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
clean_blog_social = [
    {url = "https://x.com/MostroP2P", name = "X", icon = "img/x.svg"},
    {url = "https://primal.net/p/npub1m0str0d7z2ww8rdh20t2n9lx520xjwhaq24p68umqp06wwrwtsnqen40un", name = "Nostr", icon="img/nostr.svg"},
    {url = "https://t.me/mostrop2p", name = "Telegram",icon = "img/telegram.svg"},
    {url = "https://github.com/MostroP2P", name = "Github",icon="img/github.svg"}
]
clean_blog_menu = [
    {url = "$BASE_URL", name = "Blog"},
    {url = "https://mostro.network", name = "About"},
    {url = "https://mostro.foundation", name = "Foundation"}
]
author_name = "negrunch"
